name: kontackty
description: A Command Line Contacts App to help store, retrieve and update data in a Contacts Book.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0



dev_dependencies:
  pedantic: ^1.10.0
